[package]
name = "cockpit-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
cockpit-core = { path = "../cockpit-core" }
futures.workspace = true
native-tls.workspace = true
postgres-native-tls.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
uuid.workspace = true

[dev-dependencies]
chrono.workspace = true
